os:
  - linux
language: c

before_install:
  - sudo apt-get install qemu-kvm qemu
  - git clone https://github.com/vitadev/vdpm
  - cd vdpm
  - cp config.sample config
  - ./bootstrap-vitasdk.sh
  - export VITASDK=/usr/local/vitasdk
  - export PATH=$VITASDK/bin:$PATH
  - ./install-all.sh
  - cd ..

script:
  - make
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER - $TRAVIS_OS_NAME"
  - git push -q https://$TAGPERM@github.com/frangarcj/vita3d --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file: "Vita3d.vpk"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
